apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: processing-checkpoints
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.processing.checkpointStorage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-streaming
  namespace: {{ .Values.namespace }}
  labels:
    app: processing-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing-streaming
  template:
    metadata:
      labels:
        app: processing-streaming
    spec:
      containers:
        - name: processing
          image: {{ .Values.processing.image }}
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka:9092"
            - name: KAFKA_TOPIC_IN
              value: "traffic.speeds.raw"
            - name: KAFKA_TOPIC_DLQ
              value: "traffic.speeds.dlq"
            - name: SCHEMA_PATH
              value: "/opt/spark-app/schemas/traffic_speed_event.avsc"
            - name: CHECKPOINT_DIR
              value: "/checkpoints"
            - name: MINIO_ENDPOINT
              value: "http://minio:9000"
            - name: BRONZE_TABLE_PATH
              value: "s3a://bronze/traffic_speeds_raw"
            - name: SILVER_TABLE_PATH
              value: "s3a://bronze/traffic_speeds_valid"
            - name: GOLD_TABLE_PATH
              value: "s3a://gold/congestion_scores"
          envFrom:
            - secretRef:
                name: minio-credentials
          volumeMounts:
            - name: checkpoints
              mountPath: /checkpoints
          resources:
            {{- toYaml .Values.processing.resources | nindent 12 }}
      volumes:
        - name: checkpoints
          persistentVolumeClaim:
            claimName: processing-checkpoints
